### ISSUE TITLE
Out of Memory for 5090 GPU (32GB)

### ISSUE THREAD

**Issue by luffy-yu** [Tencent-Hunyuan/HY-Motion-1.0#18]
```
(hy-motion) n10288@N10288-AAT2250:~/Documents/Code/HY-Motion-1.0$ python3 local_infer.py --model_path ckpts/tencent/HY-Motion-1.0/HY-Motion-1.0-Lite --num_seeds=1
>>> FBX module found.
>>> Initializing T2MRuntime...
>>> Loading prompter model from ckpts/Text2MotionPrompter
The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.
Loading checkpoint shards:  77%|███████████████████████████████████████████████████████▍                | 10/13 [00:18<00:05,  1.83s/it]
Traceback (most recent call last):
  File "/home/n10288/Documents/Code/HY-Motion-1.0/local_infer.py", line 395, in <module>
    main()
  File "/home/n10288/Documents/Code/HY-Motion-1.0/local_infer.py", line 341, in main
    runtime = T2MRuntime(
              ^^^^^^^^^^^
  File "/home/n10288/Documents/Code/HY-Motion-1.0/hymotion/utils/t2m_runtime.py", line 81, in __init__
    self.prompt_rewriter = PromptRewriter(
                           ^^^^^^^^^^^^^^^
  File "/home/n10288/Documents/Code/HY-Motion-1.0/hymotion/prompt_engineering/prompt_rewrite.py", line 267, in __init__
    self._load_model()
  File "/home/n10288/Documents/Code/HY-Motion-1.0/hymotion/prompt_engineering/prompt_rewrite.py", line 273, in _load_model
    self.model = AutoModelForCausalLM.from_pretrained(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/n10288/miniconda3/envs/hy-motion/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 600, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/n10288/miniconda3/envs/hy-motion/lib/python3.11/site-packages/transformers/modeling_utils.py", line 311, in _wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/n10288/miniconda3/envs/hy-motion/lib/python3.11/site-packages/transformers/modeling_utils.py", line 4839, in from_pretrained
    ) = cls._load_pretrained_model(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/n10288/miniconda3/envs/hy-motion/lib/python3.11/site-packages/transformers/modeling_utils.py", line 5302, in _load_pretrained_model
    _error_msgs, disk_offload_index, cpu_offload_index = load_shard_file(args)
                                                         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/n10288/miniconda3/envs/hy-motion/lib/python3.11/site-packages/transformers/modeling_utils.py", line 933, in load_shard_file
    disk_offload_index, cpu_offload_index = _load_state_dict_into_meta_model(
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/n10288/miniconda3/envs/hy-motion/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/n10288/miniconda3/envs/hy-motion/lib/python3.11/site-packages/transformers/modeling_utils.py", line 848, in _load_state_dict_into_meta_model
    hf_quantizer.create_quantized_param(
  File "/home/n10288/miniconda3/envs/hy-motion/lib/python3.11/site-packages/transformers/quantizers/quantizer_bnb_4bit.py", line 250, in create_quantized_param
    new_value = bnb.nn.Params4bit(new_value, requires_grad=False, **kwargs).to(target_device)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/n10288/miniconda3/envs/hy-motion/lib/python3.11/site-packages/bitsandbytes/nn/modules.py", line 346, in to
    return self._quantize(device)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/n10288/miniconda3/envs/hy-motion/lib/python3.11/site-packages/bitsandbytes/nn/modules.py", line 301, in _quantize
    w_4bit, quant_state = bnb.functional.quantize_4bit(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/n10288/miniconda3/envs/hy-motion/lib/python3.11/site-packages/bitsandbytes/functional.py", line 864, in quantize_4bit
    _out, _absmax = torch.ops.bitsandbytes.quantize_4bit.default(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/n10288/miniconda3/envs/hy-motion/lib/python3.11/site-packages/torch/_ops.py", line 829, in __call__
    return self._op(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/n10288/miniconda3/envs/hy-motion/lib/python3.11/site-packages/torch/_compile.py", line 53, in inner
    return disable_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/n10288/miniconda3/envs/hy-motion/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 929, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/n10288/miniconda3/envs/hy-motion/lib/python3.11/site-packages/torch/library.py", line 752, in func_no_dynamo
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/n10288/miniconda3/envs/hy-motion/lib/python3.11/site-packages/bitsandbytes/backends/cuda/ops.py", line 320, in _
    out = torch.empty(((n + 1) // (quant_storage.itemsize * 2), 1), device=A.device, dtype=quant_storage)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB. GPU 0 has a total capacity of 31.35 GiB of which 21.06 MiB is free. Including non-PyTorch memory, this process has 30.78 GiB memory in use. Of the allocated memory 14.22 GiB is allocated by PyTorch, and 16.00 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

```

**Comment by Yuxin-Wen** [comment]
Good to hear the inference is working now.

For the new error, we strictly require ``numpy<2.0`` right now to avoid these exact breaking changes.

Appreciate you sharing the fix for ``smplh2woodfbx.py``, though! It's good to know how to handle the migration later. I'll close this issue since the main problem is solved.
